[HOTFIX] trying to test with sonar :c

diff --git a/.github/workflows/testAndDeploy.yaml b/.github/workflows/testAndDeploy.yaml
--- a/.github/workflows/testAndDeploy.yaml
+++ b/.github/workflows/testAndDeploy.yaml
@@ -6,9 +6,51 @@ on:
       - main
 
 jobs:
+  test_and_sonarcloud:
+    name: Run Tox for tests and SonarCloud Scan
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+        
+      - name: Set up Python
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
+    
+      - name: Install dependencies
+        run: |
+            python -m pip install --upgrade pip
+            pip install tox boto3 botocore==1.27.32
+            
+      - name: Run tests and generate coverage with tox
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: us-east-2
+        run: tox
+
+      - name: Verify coverage.xml exists
+        run: |
+          if [ ! -f coverage.xml ]; then echo "coverage.xml not found"; exit 1; fi
+
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarcloud-github-action@master
+        with:
+          args: >
+            -Dsonar.projectKey=LosBaluchis_Backend_Cafe_Balu
+            -Dsonar.organization=losbaluchis
+            -Dsonar.python.coverage.reportPaths=coverage.xml
+        env:
+          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
   check-aws-credentials:
     name: Check AWS Credentials
     runs-on: ubuntu-latest
+    needs: test_and_sonarcloud
+    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }} # Solo despliega en push a la rama main
 
     steps:
       - name: Checkout code
